spring.application.name=ProfitFlow
# The database URL (localhost on your machine, port 5432 is the default PostgreSQL port)
spring.datasource.url=jdbc:postgresql://localhost:5432/profitflow
spring.datasource.username=elenabotnaru
spring.datasource.password=079180

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA configuration
# 'update' means Hibernate will automatically create/update tables on startup
spring.jpa.hibernate.ddl-auto=update

# Show SQL output in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
usda.api.key=RTWsFpTV4M9B9TaszaDITCpw67bINiAsCtTzmkUa